services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      user-service: 
        condition: service_started
      chat-service: 
        condition: service_started
      notification-service: 
        condition: service_started
    restart: always
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
  user-service:
    container_name: user-service
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    restart: always
    volumes:
      - ./services/user:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - ./services/user/.env
    networks:
      - app-network
  notification-service:
    container_name: notification-service
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - ./services/notification/.env
    restart: always
    volumes:
      - ./services/notification:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
  chat-service:
    container_name: chat-service
    build:
      context: ./services/chat
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    env_file:
      - ./services/chat/.env
    restart: always
    volumes:
      - ./services/chat:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge


