FROM python:3.14.0a5-bookworm

WORKDIR /app


# COPY . .

# RUN ls -al tsconfig.json

# RUN pip install -r requirements.txt

# EXPOSE 4003

# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "4003"]
